// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
using namespace Rcpp;

// rcpp_ecdf_transform
NumericVector rcpp_ecdf_transform(NumericVector x);
RcppExport SEXP _structureR_rcpp_ecdf_transform(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ecdf_transform(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_structureR_rcpp_ecdf_transform", (DL_FUNC) &_structureR_rcpp_ecdf_transform, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_structureR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
